# Liste massive des VIPs du football mondial (Joueurs, Entraîneurs, Agents Libres)

VIP_PLAYERS = {
    "Premier League 🏴󠁧󠁢󠁥󠁮󠁧󠁿": [
        ["Haaland", "Erling Haaland"], ["De Bruyne", "Kevin De Bruyne"], ["Rodri", "Rodrigo Hernandez"], ["Foden", "Phil Foden"], ["Bernardo", "Bernardo Silva"], ["Gvardiol", "Josko Gvardiol"], ["Dias", "Ruben Dias"], ["Ederson", "Ederson Moraes"], ["Doku", "Jeremy Doku"], ["Savinho", "Savio Moreira"], ["Kovacic", "Mateo Kovacic"], ["Akanji", "Manuel Akanji"], ["Ake", "Nathan Ake"], ["Stones", "John Stones"], ["Grealish", "Jack Grealish"], ["Nunes", "Matheus Nunes"], ["Bobb", "Oscar Bobb"],
        ["Saka", "Bukayo Saka"], ["Odegaard", "Martin Odegaard"], ["Rice", "Declan Rice"], ["Saliba", "William Saliba"], ["Gabriel", "Gabriel Magalhaes"], ["Martinelli", "Gabriel Martinelli"], ["Havertz", "Kai Havertz"], ["White", "Ben White"], ["Raya", "David Raya"], ["Merino", "Mikel Merino"], ["Calafiori", "Riccardo Calafiori"], ["Timber", "Jurrien Timber"], ["Trossard", "Leandro Trossard"], ["Jesus", "Gabriel Jesus"], ["Partey", "Thomas Partey"], ["Jorginho", "Jorginho Frello"], ["Nwaneri", "Ethan Nwaneri"],
        ["Salah", "Mohamed Salah"], ["Van Dijk", "Virgil van Dijk"], ["Alexander-Arnold", "Trent Alexander-Arnold"], ["Alisson", "Alisson Becker"], ["Mac Allister", "Alexis Mac Allister"], ["Szoboszlai", "Dominik Szoboszlai"], ["Diaz", "Luis Diaz"], ["Nunez", "Darwin Nunez"], ["Jota", "Diogo Jota"], ["Gakpo", "Cody Gakpo"], ["Gravenberch", "Ryan Gravenberch"], ["Robertson", "Andrew Robertson"], ["Konate", "Ibrahima Konate"], ["Elliott", "Harvey Elliott"], ["Jones", "Curtis Jones"], ["Bradley", "Conor Bradley"],
        ["Palmer", "Cole Palmer"], ["Fernandez", "Enzo Fernandez"], ["Caicedo", "Moises Caicedo"], ["Nkunku", "Christopher Nkunku"], ["Jackson", "Nicolas Jackson"], ["Neto", "Pedro Neto"], ["Sancho", "Jadon Sancho"], ["Felix", "Joao Felix"], ["James", "Reece James"], ["Gusto", "Malo Gusto"], ["Colwill", "Levi Colwill"], ["Fofana", "Wesley Fofana"], ["Lavia", "Romeo Lavia"], ["Madueke", "Noni Madueke"], ["Mudryk", "Mykhailo Mudryk"], ["Disasi", "Axel Disasi"], ["Badiashile", "Benoit Badiashile"],
        ["Fernandes", "Bruno Fernandes"], ["Rashford", "Marcus Rashford"], ["Garnacho", "Alejandro Garnacho"], ["Mainoo", "Kobbie Mainoo"], ["Hojlund", "Rasmus Hojlund"], ["Zirkzee", "Joshua Zirkzee"], ["De Ligt", "Matthijs de Ligt"], ["Martinez", "Lisandro Martinez"], ["Ugarte", "Manuel Ugarte"], ["Casemiro", "Carlos Casemiro"], ["Dalot", "Diogo Dalot"], ["Mazraoui", "Noussair Mazraoui"], ["Yoro", "Lenny Yoro"], ["Mount", "Mason Mount"], ["Amad", "Amad Diallo"], ["Antony", "Antony Matheus"], ["Maguire", "Harry Maguire"],
        ["Son", "Heung-min Son"], ["Maddison", "James Maddison"], ["Romero", "Cristian Romero"], ["Van de Ven", "Micky van de Ven"], ["Solanke", "Dominic Solanke"], ["Kulusevski", "Dejan Kulusevski"], ["Porro", "Pedro Porro"], ["Udogie", "Destiny Udogie"], ["Bissouma", "Yves Bissouma"], ["Sarr", "Pape Matar Sarr"], ["Bentancur", "Rodrigo Bentancur"], ["Johnson", "Brennan Johnson"], ["Richarlison", "Richarlison de Andrade"], ["Vicario", "Guglielmo Vicario"], ["Bergvall", "Lucas Bergvall"], ["Gray", "Archie Gray"],
        ["Isak", "Alexander Isak"], ["Guimaraes", "Bruno Guimaraes"], ["Gordon", "Anthony Gordon"], ["Tonali", "Sandro Tonali"], ["Botman", "Sven Botman"], ["Joelinton", "Joelinton Cassio"], ["Barnes", "Harvey Barnes"], ["Livramento", "Tino Livramento"], ["Hall", "Lewis Hall"],
        ["Watkins", "Ollie Watkins"], ["Martinez", "Emiliano Martinez"], ["Bailey", "Leon Bailey"], ["Onana", "Amadou Onana"], ["Tielemans", "Youri Tielemans"], ["McGinn", "John McGinn"], ["Rogers", "Morgan Rogers"], ["Duran", "Jhon Duran"], ["Maatsen", "Ian Maatsen"], ["Consa", "Ezri Konsa"],
        ["Bowen", "Jarrod Bowen"], ["Kudus", "Mohammed Kudus"], ["Paqueta", "Lucas Paqueta"], ["Summerville", "Crysencio Summerville"], ["Fullkrug", "Niclas Fullkrug"], ["Todibo", "Jean-Clair Todibo"], ["Kilman", "Max Kilman"], ["Alvarez", "Edson Alvarez"], ["Wan-Bissaka", "Aaron Wan-Bissaka"],
        ["Mitoma", "Kaoru Mitoma"], ["Pedro", "Joao Pedro"], ["Rutter", "Georginio Rutter"], ["Minteh", "Yankuba Minteh"], ["Ferguson", "Evan Ferguson"], ["Baleba", "Carlos Baleba"], ["Enciso", "Julio Enciso"], ["Estupinan", "Pervis Estupinan"], ["Wieffer", "Mats Wieffer"],
        ["Eze", "Eberechi Eze"], ["Guehi", "Marc Guehi"], ["Mateta", "Jean-Philippe Mateta"], ["Wharton", "Adam Wharton"], ["Lacroix", "Maxence Lacroix"], ["Kamada", "Daichi Kamada"], ["Sarr", "Ismaila Sarr"],
        ["Mbeumo", "Bryan Mbeumo"], ["Wissa", "Yoane Wissa"], ["Carvalho", "Fabio Carvalho"], ["Cunha", "Matheus Cunha"], ["Gomes", "Joao Gomes"], ["Ait-Nouri", "Rayan Ait-Nouri"], ["Lemina", "Mario Lemina"], ["Strand Larsen", "Jorgen Strand Larsen"],
        ["Gibbs-White", "Morgan Gibbs-White"], ["Elanga", "Anthony Elanga"], ["Hudson-Odoi", "Callum Hudson-Odoi"], ["Murillo", "Murillo Santiago"], ["Milenkovic", "Nikola Milenkovic"], ["Robinson", "Antonee Robinson"], ["Smith Rowe", "Emile Smith Rowe"], ["Iwobi", "Alex Iwobi"], ["Pereira", "Andreas Pereira"], ["Traore", "Adama Traore"]
    ],
    "La Liga 🇪🇸": [
        ["Mbappé", "Kylian Mbappé"], ["Vinicius", "Vinicius Junior"], ["Bellingham", "Jude Bellingham"], ["Rodrygo", "Rodrygo Goes"], ["Valverde", "Federico Valverde"], ["Camavinga", "Eduardo Camavinga"], ["Tchouaméni", "Aurélien Tchouaméni"], ["Güler", "Arda Güler"], ["Endrick", "Endrick Felipe"], ["Brahim", "Brahim Diaz"], ["Courtois", "Thibaut Courtois"], ["Militao", "Eder Militao"], ["Rudiger", "Antonio Rudiger"], ["Alaba", "David Alaba"], ["Carvajal", "Dani Carvajal"], ["Mendy", "Ferland Mendy"], ["Modric", "Luka Modric"], ["Ceballos", "Dani Ceballos"], ["Garcia", "Fran Garcia"], ["Paz", "Nico Paz"],
        ["Yamal", "Lamine Yamal"], ["Lewandowski", "Robert Lewandowski"], ["Pedri", "Pedri Gonzalez"], ["Gavi", "Pablo Gavi"], ["Raphinha", "Raphinha Belloli"], ["Olmo", "Dani Olmo"], ["Araujo", "Ronald Araujo"], ["Cubarsi", "Pau Cubarsi"], ["Kounde", "Jules Kounde"], ["Balde", "Alejandro Balde"], ["De Jong", "Frenkie de Jong"], ["Ter Stegen", "Marc-Andre ter Stegen"], ["Casado", "Marc Casado"], ["Fermin", "Fermin Lopez"], ["Torres", "Ferran Torres"], ["Fati", "Ansu Fati"], ["Christensen", "Andreas Christensen"], ["Garcia", "Eric Garcia"],
        ["Griezmann", "Antoine Griezmann"], ["Alvarez", "Julian Alvarez"], ["Sørloth", "Alexander Sørloth"], ["De Paul", "Rodrigo De Paul"], ["Gallagher", "Conor Gallagher"], ["Oblak", "Jan Oblak"], ["Koke", "Jorge Resurreccion"], ["Llorente", "Marcos Llorente"], ["Gimenez", "Jose Maria Gimenez"], ["Le Normand", "Robin Le Normand"], ["Barrios", "Pablo Barrios"], ["Lino", "Samuel Lino"], ["Riquelme", "Rodrigo Riquelme"], ["Lenglet", "Clement Lenglet"], ["Correa", "Angel Correa"],
        ["Williams", "Nico Williams"], ["Williams", "Inaki Williams"], ["Sancet", "Oihan Sancet"], ["Simon", "Unai Simon"], ["Vivian", "Dani Vivian"], ["Paredes", "Aitor Paredes"], ["Berenguer", "Alex Berenguer"], ["Herrera", "Ander Herrera"],
        ["Kubo", "Takefusa Kubo"], ["Oyarzabal", "Mikel Oyarzabal"], ["Zubimendi", "Martin Zubimendi"], ["Brais", "Brais Mendez"], ["Remiro", "Alex Remiro"], ["Zubeldia", "Igor Zubeldia"], ["Barrenetxea", "Ander Barrenetxea"], ["Sucic", "Luka Sucic"], ["Becker", "Sheraldo Becker"],
        ["Perez", "Ayoze Perez"], ["Baena", "Alex Baena"], ["Gerard", "Gerard Moreno"], ["Parejo", "Dani Parejo"], ["Yeremy", "Yeremy Pino"], ["Conde", "Diego Conde"], ["Isco", "Isco Alarcon"], ["Lo Celso", "Giovani Lo Celso"], ["Fornals", "Pablo Fornals"], ["Abde", "Ez Abde"], ["Roca", "Marc Roca"], ["Bellerin", "Hector Bellerin"], ["Vitor Roque", "Vitor Roque"],
        ["Tsygankov", "Viktor Tsygankov"], ["Girona", "Yaser Asprilla"], ["Ruiz", "Abel Ruiz"], ["Danjuma", "Arnaut Danjuma"], ["Guerra", "Javi Guerra"], ["Pepelu", "Jose Luis Garcia"], ["Mamardashvili", "Giorgi Mamardashvili"], ["Duro", "Hugo Duro"], ["Gayia", "Jose Gaya"], ["Aspas", "Iago Aspas"], ["Mingueza", "Oscar Mingueza"], ["Douvikas", "Anastasios Douvikas"], ["Muriqi", "Vedat Muriqi"], ["Darder", "Sergi Darder"]
    ],
    "Serie A 🇮🇹": [
        ["Lautaro", "Lautaro Martinez"], ["Barella", "Nicolo Barella"], ["Thuram", "Marcus Thuram"], ["Bastoni", "Alessandro Bastoni"], ["Calhanoglu", "Hakan Calhanoglu"], ["Dimarco", "Federico Dimarco"], ["Pavard", "Benjamin Pavard"], ["Sommer", "Yann Sommer"], ["Frattesi", "Davide Frattesi"], ["Zielinski", "Piotr Zielinski"], ["Mkhitaryan", "Henrikh Mkhitaryan"], ["Dumfries", "Denzel Dumfries"], ["Acerbi", "Francesco Acerbi"], ["De Vrij", "Stefan de Vrij"], ["Taremi", "Mehdi Taremi"], ["Asllani", "Kristjan Asllani"],
        ["Leao", "Rafael Leao"], ["Hernandez", "Theo Hernandez"], ["Pulisic", "Christian Pulisic"], ["Maignan", "Mike Maignan"], ["Morata", "Alvaro Morata"], ["Fofana", "Youssouf Fofana"], ["Reijnders", "Tijjani Reijnders"], ["Tomori", "Fikayo Tomori"], ["Pavlovic", "Strahinja Pavlovic"], ["Loftus-Cheek", "Ruben Loftus-Cheek"], ["Chukwueze", "Samuel Chukwueze"], ["Okafor", "Noah Okafor"], ["Calabria", "Davide Calabria"], ["Bennacer", "Ismael Bennacer"], ["Emerson", "Emerson Royal"],
        ["Vlahovic", "Dusan Vlahovic"], ["Yildiz", "Kenan Yildiz"], ["Bremer", "Gleison Bremer"], ["Koopmeiners", "Teun Koopmeiners"], ["Douglas Luiz", "Douglas Luiz"], ["Thuram", "Khephren Thuram"], ["Cambiaso", "Andrea Cambiaso"], ["Nico Gonzalez", "Nicolas Gonzalez"], ["Conceicao", "Francisco Conceicao"], ["Locatelli", "Manuel Locatelli"], ["Di Gregorio", "Michele Di Gregorio"], ["Kalulu", "Pierre Kalulu"], ["Gatti", "Federico Gatti"], ["Fagioli", "Nicolò Fagioli"], ["Weah", "Timothy Weah"],
        ["Kvaratskhelia", "Khvicha Kvaratskhelia"], ["Lukaku", "Romelu Lukaku"], ["McTominay", "Scott McTominay"], ["Buongiorno", "Alessandro Buongiorno"], ["Di Lorenzo", "Giovanni Di Lorenzo"], ["Lobotka", "Stanislav Lobotka"], ["Anguissa", "Andre-Frank Zambo Anguissa"], ["Meret", "Alex Meret"], ["Politano", "Matteo Politano"], ["Neres", "David Neres"], ["Gilmour", "Billy Gilmour"], ["Spinazzola", "Leonardo Spinazzola"], ["Rrahmani", "Amir Rrahmani"],
        ["Dybala", "Paulo Dybala"], ["Soulé", "Matias Soule"], ["Dovbyk", "Artem Dovbyk"], ["Pellegrini", "Lorenzo Pellegrini"], ["Mancini", "Gianluca Mancini"], ["Ndicka", "Evan Ndicka"], ["Svilar", "Mile Svilar"], ["Kone", "Manu Kone"], ["El Shaarawy", "Stephan El Shaarawy"], ["Cristante", "Bryan Cristante"], ["Saelemaekers", "Alexis Saelemaekers"], ["Le Fee", "Enzo Le Fee"],
        ["Zaccagni", "Mattia Zaccagni"], ["Guendouzi", "Matteo Guendouzi"], ["Castellanos", "Taty Castellanos"], ["Dia", "Boulaye Dia"], ["Provedel", "Ivan Provedel"], ["Romagnoli", "Alessio Romagnoli"], ["Tavares", "Nuno Tavares"], ["Rovella", "Nicolò Rovella"], ["Lookman", "Ademola Lookman"], ["De Ketelaere", "Charles De Ketelaere"], ["Retegui", "Mateo Retegui"], ["Ederson", "Ederson dos Santos"], ["Pasalic", "Mario Pasalic"], ["Samardzic", "Lazar Samardzic"], ["Scalvini", "Giorgio Scalvini"], ["Carnesecchi", "Marco Carnesecchi"], ["Zaniolo", "Nicolo Zaniolo"],
        ["Gudmundsson", "Albert Gudmundsson"], ["Kean", "Moise Kean"], ["Colpani", "Andrea Colpani"], ["De Gea", "David de Gea"], ["Biraghi", "Cristiano Biraghi"], ["Dodo", "Dodo Domilson"], ["Beltran", "Lucas Beltran"], ["Bove", "Edoardo Bove"], ["Adli", "Yacine Adli"],
        ["Zapata", "Duvan Zapata"], ["Ricci", "Samuele Ricci"], ["Ilic", "Ivan Ilic"], ["Sanabria", "Antonio Sanabria"], ["Orsolini", "Riccardo Orsolini"], ["Ndoye", "Dan Ndoye"], ["Castro", "Santiago Castro"], ["Fabbian", "Giovanni Fabbian"], ["Posch", "Stefan Posch"], ["Lucumi", "Jhon Lucumi"],
        ["Pinamonti", "Andrea Pinamonti"], ["Thauvin", "Florian Thauvin"], ["Lucca", "Lorenzo Lucca"], ["Bijol", "Jaka Bijol"], ["Lovric", "Sandi Lovric"], ["Pessina", "Matteo Pessina"], ["Maldini", "Daniel Maldini"], ["Djuric", "Milan Djuric"], ["Krstovic", "Nikola Krstovic"], ["Dorgu", "Patrick Dorgu"], ["Bongiorno", "Lameck Banda"], ["Oristanio", "Gaetano Oristanio"], ["Man", "Dennis Man"], ["Mihaila", "Valentin Mihaila"], ["Bernabe", "Adrian Bernabe"], ["Bonny", "Ange-Yoan Bonny"]
    ],
    "Bundesliga 🇩🇪": [
        ["Kane", "Harry Kane"], ["Musiala", "Jamal Musiala"], ["Wirtz", "Florian Wirtz"], ["Sane", "Leroy Sane"], ["Kimmich", "Joshua Kimmich"], ["Davies", "Alphonso Davies"], ["Olise", "Michael Olise"], ["Upamecano", "Dayot Upamecano"], ["Kim", "Min-jae Kim"], ["Neuer", "Manuel Neuer"], ["Palhinha", "Joao Palhinha"], ["Pavlovic", "Aleksandar Pavlovic"], ["Gnabry", "Serge Gnabry"], ["Coman", "Kingsley Coman"], ["Muller", "Thomas Muller"], ["Goretzka", "Leon Goretzka"], ["Tel", "Mathys Tel"], ["Boey", "Sacha Boey"], ["Ito", "Hiroki Ito"], ["Stanisic", "Josip Stanisic"], ["Laimer", "Konrad Laimer"],
        ["Frimpong", "Jeremie Frimpong"], ["Grimaldo", "Alejandro Grimaldo"], ["Boniface", "Victor Boniface"], ["Xhaka", "Granit Xhaka"], ["Tah", "Jonathan Tah"], ["Tapsoba", "Edmond Tapsoba"], ["Hincapie", "Piero Hincapie"], ["Palacios", "Exequiel Palacios"], ["Garcia", "Aleix Garcia"], ["Terrier", "Martin Terrier"], ["Adli", "Amine Adli"], ["Schick", "Patrik Schick"], ["Tella", "Nathan Tella"], ["Andrich", "Robert Andrich"], ["Hradecky", "Lukas Hradecky"],
        ["Simons", "Xavi Simons"], ["Sesko", "Benjamin Sesko"], ["Openda", "Lois Openda"], ["Orban", "Willi Orban"], ["Lukeba", "Castello Lukeba"], ["Raum", "David Raum"], ["Henrichs", "Benjamin Henrichs"], ["Schlager", "Xaver Schlager"], ["Haidara", "Amadou Haidara"], ["Seiwald", "Nicolas Seiwald"], ["Nusa", "Antonio Nusa"], ["Vermeeren", "Arthur Vermeeren"], ["Gulacsi", "Peter Gulacsi"], ["Baumgartner", "Christoph Baumgartner"], ["Elmas", "Eljif Elmas"], ["Poulsen", "Yussuf Poulsen"],
        ["Brandt", "Julian Brandt"], ["Guirassy", "Serhou Guirassy"], ["Adeyemi", "Karim Adeyemi"], ["Malen", "Donyell Malen"], ["Sabitzer", "Marcel Sabitzer"], ["Can", "Emre Can"], ["Schlotterbeck", "Nico Schlotterbeck"], ["Anton", "Waldemar Anton"], ["Sule", "Niklas Sule"], ["Couto", "Yan Couto"], ["Ryerson", "Julian Ryerson"], ["Kobel", "Gregor Kobel"], ["Beier", "Maximilian Beier"], ["Gittens", "Jamie Gittens"], ["Gross", "Pascal Gross"], ["Nmecha", "Felix Nmecha"], ["Reyna", "Giovanni Reyna"], ["Duranville", "Julien Duranville"],
        ["Undav", "Deniz Undav"], ["Demirovic", "Ermedin Demirovic"], ["Millot", "Enzo Millot"], ["Stiller", "Angelo Stiller"], ["Karazor", "Atakan Karazor"], ["Mittelstadt", "Maximilian Mittelstadt"], ["Nubell", "Alexander Nubel"], ["Leweling", "Jamie Leweling"], ["Touré", "El Bilal Toure"], ["Vagnoman", "Josha Vagnoman"], ["Zagadou", "Dan-Axel Zagadou"],
        ["Marmoush", "Omar Marmoush"], ["Ekitike", "Hugo Ekitike"], ["Gotze", "Mario Gotze"], ["Larsson", "Hugo Larsson"], ["Chaibi", "Fares Chaibi"], ["Koch", "Robin Koch"], ["Trapp", "Kevin Trapp"], ["Theate", "Arthur Theate"], ["Kristensen", "Rasmus Kristensen"],
        ["Pleas", "Alassane Plea"], ["Honorat", "Franck Honorat"], ["Kleindienst", "Tim Kleindienst"], ["Stoger", "Kevin Stoger"], ["Itakura", "Ko Itakura"], ["Weigl", "Julian Weigl"], ["Scally", "Joe Scally"], ["Elvedi", "Nico Elvedi"],
        ["Majer", "Lovro Majer"], ["Wind", "Jonas Wind"], ["Amoura", "Mohamed Amoura"], ["Arnold", "Maximilian Arnold"], ["Maehle", "Joakim Maehle"], ["Lacroix", "Maxence Lacroix"],
        ["Duan", "Ritsu Doan"], ["Grifo", "Vincenzo Grifo"], ["Eggestein", "Maximilian Eggestein"], ["Ginter", "Matthias Ginter"], ["Lienhart", "Philipp Lienhart"],
        ["Kramaric", "Andrej Kramaric"], ["Hlozek", "Adam Hlozek"], ["Berisha", "Mergim Berisha"], ["Baumann", "Oliver Baumann"], ["Bebou", "Ihlas Bebou"], ["Akpoguma", "Kevin Akpoguma"],
        ["Ducksch", "Marvin Ducksch"], ["Schmid", "Romano Schmid"], ["Stage", "Jens Stage"], ["Weiser", "Mitchell Weiser"],
        ["Burkardt", "Jonathan Burkardt"], ["Lee", "Jae-sung Lee"], ["Amiri", "Nadiem Amiri"], ["Zentner", "Robin Zentner"]
    ],
    "Ligue 1 🇫🇷": [
        ["Dembele", "Ousmane Dembele"], ["Barcola", "Bradley Barcola"], ["Vitinha", "Vitor Machado"], ["Hakimi", "Achraf Hakimi"], ["Neves", "Joao Neves"], ["Zaire-Emery", "Warren Zaire-Emery"], ["Marquinhos", "Marquinhos Correa"], ["Donnarumma", "Gianluigi Donnarumma"], ["Mendes", "Nuno Mendes"], ["Doué", "Désiré Doué"], ["Ramos", "Goncalo Ramos"], ["Asensio", "Marco Asensio"], ["Lee", "Kang-in Lee"], ["Ruiz", "Fabian Ruiz"], ["Pacho", "Willian Pacho"], ["Beraldo", "Lucas Beraldo"], ["Hernandez", "Lucas Hernandez"], ["Kimpembe", "Presnel Kimpembe"], ["Safonov", "Matvey Safonov"], ["Kolo Muani", "Randal Kolo Muani"], ["Skriniar", "Milan Skriniar"],
        ["Greenwood", "Mason Greenwood"], ["Wahi", "Elye Wahi"], ["Hojbjerg", "Pierre-Emile Hojbjerg"], ["Rabiot", "Adrien Rabiot"], ["Rowe", "Jonathan Rowe"], ["Harit", "Amine Harit"], ["Merlin", "Quentin Merlin"], ["Balerdi", "Leonardo Balerdi"], ["Rulli", "Geronimo Rulli"], ["Carboni", "Valentin Carboni"], ["Kondogbia", "Geoffrey Kondogbia"], ["Murillo", "Michael Murillo"], ["Brassier", "Lilian Brassier"], ["Koné", "Ismael Kone"], ["Maupay", "Neal Maupay"], ["Luis Henrique", "Luis Henrique"], ["Rongier", "Valentin Rongier"], ["Mbemba", "Chancel Mbemba"],
        ["David", "Jonathan David"], ["Zhegrova", "Edon Zhegrova"], ["Sahraoui", "Osame Sahraoui"], ["Angel Gomes", "Angel Gomes"], ["Andre", "Benjamin Andre"], ["Chevalier", "Lucas Chevalier"], ["Diakite", "Bafode Diakite"], ["Alexsandro", "Alexsandro Ribeiro"], ["Meunier", "Thomas Meunier"], ["Santos", "Tiago Santos"], ["Haraldsson", "Hakon Haraldsson"], ["Bakker", "Mitchel Bakker"], ["Bayo", "Mohamed Bayo"], ["Bouaddi", "Ayyoub Bouaddi"],
        ["Ben Seghir", "Eliesse Ben Seghir"], ["Akliouche", "Maghnes Akliouche"], ["Embolo", "Breel Embolo"], ["Balogun", "Folarin Balogun"], ["Minamino", "Takumi Minamino"], ["Golovin", "Aleksandr Golovin"], ["Zakaria", "Denis Zakaria"], ["Camara", "Lamine Camara"], ["Vanderson", "Vanderson de Oliveira"], ["Singo", "Wilfried Singo"], ["Salisu", "Mohammed Salisu"], ["Kehrer", "Thilo Kehrer"], ["Kohn", "Philipp Kohn"], ["Ilenikhena", "George Ilenikhena"], ["Diata", "Krepin Diatta"],
        ["Lacazette", "Alexandre Lacazette"], ["Mikautadze", "Georges Mikautadze"], ["Cherki", "Rayan Cherki"], ["Fofana", "Malick Fofana"], ["Benrahma", "Said Benrahma"], ["Nuamah", "Ernest Nuamah"], ["Matic", "Nemanja Matic"], ["Tolisso", "Corentin Tolisso"], ["Caqueret", "Maxence Caqueret"], ["Veretout", "Jordan Veretout"], ["Niakhate", "Moussa Niakhate"], ["Caleta-Car", "Duje Caleta-Car"], ["Tagliafico", "Nicolas Tagliafico"], ["Maitland-Niles", "Ainsley Maitland-Niles"], ["Perri", "Lucas Perri"], ["Abner", "Abner Vinicius"],
        ["Guessand", "Evann Guessand"], ["Moukoko", "Youssoufa Moukoko"], ["Boga", "Jeremie Boga"], ["Cho", "Mohamed-Ali Cho"], ["Laborde", "Gaetan Laborde"], ["Ndombele", "Tanguy Ndombele"], ["Rosario", "Pablo Rosario"], ["Boudaoui", "Hicham Boudaoui"], ["Dante", "Dante Bonfim"], ["Bombito", "Moise Bombito"], ["Clauss", "Jonathan Clauss"], ["Bard", "Melvin Bard"], ["Bulka", "Marcin Bulka"],
        ["Sotoca", "Florian Sotoca"], ["Nzola", "Mbala Nzola"], ["Saïd", "Wesley Said"], ["Thomasson", "Adrien Thomasson"], ["Diouf", "Andy Diouf"], ["El Aynaoui", "Neil El Aynaoui"], ["Danso", "Kevin Danso"], ["Medina", "Facundo Medina"], ["Gradit", "Jonathan Gradit"], ["Frankowski", "Przemyslaw Frankowski"], ["Machado", "Deiver Machado"], ["Samba", "Brice Samba"], ["Zaroury", "Anass Zaroury"], ["Chavez", "Jhoanner Chavez"],
        ["Kalimuendo", "Arnaud Kalimuendo"], ["Gouiri", "Amine Gouiri"], ["Blas", "Ludovic Blas"], ["Grønbæk", "Albert Gronbaek"], ["Jota", "Jota Silva"], ["Matusiwa", "Azor Matusiwa"], ["Santamaria", "Baptiste Santamaria"], ["Kamara", "Glen Kamara"], ["Wooh", "Christopher Wooh"], ["Seidu", "Alidu Seidu"], ["Truffert", "Adrien Truffert"], ["Assignon", "Lorenz Assignon"], ["Mandanda", "Steve Mandanda"], ["Østigård", "Leo Ostigard"],
        ["Ajorque", "Ludovic Ajorque"], ["Del Castillo", "Romain Del Castillo"], ["Sima", "Abdallah Sima"], ["Baldé", "Mama Balde"], ["Camara", "Mahdi Camara"], ["Magnetti", "Hugo Magnetti"], ["Lees-Melou", "Pierre Lees-Melou"], ["Chardonnet", "Brendan Chardonnet"], ["Lala", "Kenny Lala"], ["Bizot", "Marco Bizot"],
        ["Emegha", "Emanuel Emegha"], ["Nanasi", "Sebastian Nanasi"], ["Bakwa", "Dilane Bakwa"], ["Santos", "Andrey Santos"], ["Doukouré", "Ismael Doukoure"], ["Sylla", "Abakar Sylla"], ["Petrovic", "Djordje Petrovic"], ["Moreira", "Diego Moreira"],
        ["Dallinga", "Thijs Dallinga"], ["Aboukhlal", "Zakaria Aboukhlal"], ["Gboho", "Yann Gboho"], ["Sierro", "Vincent Sierro"], ["Restes", "Guillaume Restes"], ["Nicolaisen", "Rasmus Nicolaisen"], ["Suazo", "Gabriel Suazo"],
        ["Moses Simon", "Moses Simon"], ["Abline", "Matthis Abline"], ["Kadewere", "Tino Kadewere"], ["Chirivella", "Pedro Chirivella"], ["Douglas Augusto", "Douglas Augusto"], ["Castelletto", "Jean-Charles Castelletto"], ["Lafont", "Alban Lafont"],
        ["Adams", "Akor Adams"], ["Al-Taamari", "Musa Al-Taamari"], ["Savanier", "Téji Savanier"], ["Ferri", "Jordan Ferri"], ["Chotard", "Joris Chotard"], ["Sagnan", "Modibo Sagnan"], ["Lecomte", "Benjamin Lecomte"],
        ["Nakamura", "Keito Nakamura"], ["Ito", "Junya Ito"], ["Diakité", "Oumar Diakite"], ["Munetsi", "Marshall Munetsi"], ["Teuma", "Teddy Teuma"], ["Agbadou", "Emmanuel Agbadou"], ["Diouf", "Yehvann Diouf"],
        ["Perrin", "Gaetan Perrin"], ["Sinayoko", "Lassine Sinayoko"], ["Traorè", "Hamed Junior Traore"], ["Jubal", "Jubal Junior"], ["Leon", "Donovan Leon"],
        ["Davitashvili", "Zuriko Davitashvili"], ["Sissoko", "Ibrahim Sissoko"], ["Cafaro", "Mathieu Cafaro"], ["Abdelhamid", "Yunis Abdelhamid"], ["Larsonneur", "Gautier Larsonneur"]
    ],
    "Saudi Pro League 🇸🇦": [
        ["Ronaldo", "Cristiano Ronaldo"], ["Mané", "Sadio Mane"], ["Talisca", "Anderson Talisca"], ["Brozovic", "Marcelo Brozovic"], ["Otavio", "Otavio Monteiro"], ["Simakan", "Mohamed Simakan"], ["Laporte", "Aymeric Laporte"], ["Bento", "Bento Krepski"], ["Ghareeb", "Abdulrahman Ghareeb"], ["Wesley", "Wesley Gassova"], ["Angelo", "Angelo Gabriel"], ["Al-Ghannam", "Sultan Al-Ghannam"], ["Al-Khaibari", "Abdullah Al-Khaibari"],
        ["Neymar", "Neymar Jr"], ["Mitrovic", "Aleksandar Mitrovic"], ["Malcom", "Malcom Filipe"], ["Milinkovic-Savic", "Sergej Milinkovic-Savic"], ["Neves", "Ruben Neves"], ["Cancelo", "Joao Cancelo"], ["Koulibaly", "Kalidou Koulibaly"], ["Bounou", "Yassine Bounou"], ["Lodi", "Renan Lodi"], ["Leonardo", "Marcos Leonardo"], ["Al-Dawsari", "Salem Al-Dawsari"], ["Kanno", "Mohamed Kanno"], ["Al-Burayk", "Mohammed Al-Burayk"],
        ["Benzema", "Karim Benzema"], ["Diaby", "Moussa Diaby"], ["Aouar", "Houssem Aouar"], ["Kanté", "N'Golo Kante"], ["Fabinho", "Fabinho Tavares"], ["Bergwijn", "Steven Bergwijn"], ["Danilo", "Danilo Pereira"], ["Rajkovic", "Predrag Rajkovic"], ["Mitaj", "Mario Mitaj"], ["Al-Shehri", "Saleh Al-Shehri"],
        ["Mahrez", "Riyad Mahrez"], ["Toney", "Ivan Toney"], ["Firmino", "Roberto Firmino"], ["Veiga", "Gabri Veiga"], ["Kessie", "Franck Kessie"], ["Ibanez", "Roger Ibanez"], ["Demiral", "Merih Demiral"], ["Mendy", "Edouard Mendy"], ["Alexsander", "Alexsander Gomes"], ["Al-Buraikan", "Firas Al-Buraikan"],
        ["Aubameyang", "Pierre-Emerick Aubameyang"], ["Nacho", "Nacho Fernandez"], ["Quinones", "Julian Quinones"], ["Casteels", "Koen Casteels"], ["Nandez", "Nahitan Nandez"], ["Al-Muwallad", "Fahad Al-Muwallad"],
        ["Carrasco", "Yannick Carrasco"], ["Dembélé", "Moussa Dembele"], ["Bonaventura", "Giacomo Bonaventura"], ["Wijnaldum", "Georginio Wijnaldum"], ["Hendry", "Jack Hendry"],
        ["Gerard", "Steven Gerrard"], ["Dembele", "Moussa Dembele"], ["Ekambi", "Karl Toko Ekambi"], ["Wijnaldum", "Georginio Wijnaldum"], ["Gray", "Demarai Gray"],
        ["Zouma", "Kurt Zouma"], ["Stanciu", "Nicolae Stanciu"], ["Onyekuru", "Henry Onyekuru"],
        ["Barrow", "Musa Barrow"], ["López", "Lisandro Lopez"], ["Medran", "Alvaro Medran"],
        ["Diallo", "Habib Diallo"], ["Hamdallah", "Abderrazak Hamdallah"], ["Coello", "Alex Collado"],
        ["Cordoba", "Jhon Cordoba"], ["Guiri", "Amine Gouiri"]
    ],
    "Pépites & Marchés Secondaires 🌟": [
        ["Gyokeres", "Viktor Gyokeres"], ["Hjulmand", "Morten Hjulmand"], ["Inacio", "Goncalo Inacio"], ["Diomande", "Ousmane Diomande"], ["Debast", "Zeno Debast"], ["Trincao", "Francisco Trincao"], ["Goncalves", "Pedro Goncalves"], ["Catamo", "Geny Catamo"], ["Harder", "Conrad Harder"], ["Quenda", "Geovany Quenda"],
        ["Kokcu", "Orkun Kokcu"], ["Akturkoglu", "Kerem Akturkoglu"], ["Pavlidis", "Vangelis Pavlidis"], ["Silva", "Antonio Silva"], ["Otamendi", "Nicolas Otamendi"], ["Carreras", "Alvaro Carreras"], ["Aursnes", "Fredrik Aursnes"], ["Florentino", "Florentino Luis"], ["Schjelderup", "Andreas Schjelderup"], ["Rollheiser", "Benjamín Rollheiser"], ["Prestianni", "Gianluca Prestianni"],
        ["Samu", "Samu Omorodion"], ["Galeno", "Wenderson Galeno"], ["Pepe", "Pepe Aquino"], ["Varela", "Alan Varela"], ["Gonzalez", "Nico Gonzalez"], ["Costa", "Diogo Costa"], ["Moura", "Francisco Moura"], ["Mario", "Joao Mario"],
        ["Bakayoko", "Johan Bakayoko"], ["De Jong", "Luuk de Jong"], ["Til", "Guus Til"], ["Veerman", "Joey Veerman"], ["Schouten", "Jerdy Schouten"], ["Boscagli", "Olivier Boscagli"], ["Flamingo", "Ryan Flamingo"], ["Benitez", "Walter Benitez"], ["Tillman", "Malik Tillman"], ["Pepi", "Ricardo Pepi"],
        ["Brobbey", "Brian Brobbey"], ["Weghorst", "Wout Weghorst"], ["Akpom", "Chuba Akpom"], ["Taylor", "Kenneth Taylor"], ["Henderson", "Jordan Henderson"], ["Hato", "Jorrel Hato"], ["Sutalo", "Josip Sutalo"], ["Pasveer", "Remko Pasveer"], ["Traore", "Bertrand Traore"], ["Godts", "Mika Godts"],
        ["Gimenez", "Santiago Gimenez"], ["Paixao", "Igor Paixao"], ["Ueda", "Ayase Ueda"], ["Timber", "Quinten Timber"], ["Hwang", "In-beom Hwang"], ["Hancko", "David Hancko"], ["Beelen", "Thomas Beelen"], ["Hartman", "Quilindschy Hartman"], ["Milambo", "Antoni Milambo"],
        ["Estevao", "Estevao Willian"], ["Endrick", "Endrick Felipe"], ["Lorran", "Lorran Lucas"], ["Wesley", "Wesley Gassova"], ["Mastantuono", "Franco Mastantuono"], ["Echeverri", "Claudio Echeverri"], ["Ruberto", "Agustin Ruberto"], ["Beraldo", "Lucas Beraldo"], ["Subiabre", "Ian Subiabre"], ["Souza", "Rayyan Souza"],
        ["Brahim", "Brahim Diaz"], ["Hakimi", "Achraf Hakimi"], ["Ziyech", "Hakim Ziyech"], ["Aguerd", "Nayef Aguerd"], ["Bounou", "Yassine Bounou"], ["En-Nesyri", "Youssef En-Nesyri"], ["Saibari", "Ismael Saibari"], ["El Kaabi", "Ayoub El Kaabi"], ["Adli", "Amine Adli"], ["Richardson", "Amir Richardson"], ["Ben Seghir", "Eliesse Ben Seghir"], ["El Khannouss", "Bilal El Khannouss"], ["Amrabat", "Sofyan Amrabat"], ["Ounahi", "Azzedine Ounahi"], ["Mazraoui", "Noussair Mazraoui"], ["Abde", "Ez Abde"], ["Akhomach", "Ilias Akhomach"], ["Zaroury", "Anass Zaroury"], ["Chadi Riad", "Chadi Riad"], ["Rahimi", "Soufiane Rahimi"], ["El Aynaoui", "Neil El Aynaoui"], ["Aboukhlal", "Zakaria Aboukhlal"], ["Tissoudali", "Tarik Tissoudali"], ["Dari", "Achraf Dari"],
        ["Messi", "Lionel Messi"], ["Suarez", "Luis Suarez"], ["Busquets", "Sergio Busquets"], ["Alba", "Jordi Alba"], ["Redondo", "Federico Redondo"], ["Gomez", "Diego Gomez"], ["Giroud", "Olivier Giroud"], ["Lloris", "Hugo Lloris"], ["Bouanga", "Denis Bouanga"], ["Bernardeschi", "Federico Bernardeschi"], ["Benteke", "Christian Benteke"], ["Puig", "Riqui Puig"], ["Evander", "Evander da Silva"], ["Forsberg", "Emil Forsberg"], ["Reus", "Marco Reus"], ["Acosta", "Luciano Acosta"]
    ]
}

VIP_MANAGERS = {
    "Top Managers & Entraîneurs 👔": [
        ["Guardiola", "Pep Guardiola"], ["Ancelotti", "Carlo Ancelotti"], ["Arteta", "Mikel Arteta"], ["Luis Enrique", "Luis Enrique Martinez"], ["Xabi Alonso", "Xabi Alonso"], ["Klopp", "Jürgen Klopp"], ["Flick", "Hansi Flick"], ["Mourinho", "José Mourinho"], ["Simeone", "Diego Simeone"], ["Slot", "Arne Slot"], ["Maresca", "Enzo Maresca"], ["Amorim", "Rúben Amorim"], ["Postecoglou", "Ange Postecoglou"], ["De Zerbi", "Roberto De Zerbi"], ["Emery", "Unai Emery"], ["Howe", "Eddie Howe"], ["Kompany", "Vincent Kompany"], ["Rose", "Marco Rose"], ["Sahin", "Nuri Sahin"], ["Iraola", "Andoni Iraola"], ["Hurzeler", "Fabian Hürzeler"], ["McKenna", "Kieran McKenna"], ["Frank", "Thomas Frank"], ["Silva", "Marco Silva"], ["Dyche", "Sean Dyche"], ["O'Neil", "Gary O'Neil"], ["Glasner", "Oliver Glasner"], ["Cooper", "Steve Cooper"],
        ["Inzaghi", "Simone Inzaghi"], ["Conte", "Antonio Conte"], ["Motta", "Thiago Motta"], ["Gasperini", "Gian Piero Gasperini"], ["Baroni", "Marco Baroni"], ["Palladino", "Raffaele Palladino"], ["Italiano", "Vincenzo Italiano"], ["Gilardino", "Alberto Gilardino"], ["Fabregas", "Cesc Fàbregas"], ["Nesta", "Alessandro Nesta"], ["Runjaic", "Kosta Runjaic"], ["Zanetti", "Paolo Zanetti"], ["Pecchia", "Fabio Pecchia"], ["Jorge Jesus", "Jorge Jesus"], ["Pioli", "Stefano Pioli"], ["Conceição", "Sérgio Conceição"], ["Galtier", "Christophe Galtier"], ["Michel", "Míchel Gonzalez"], ["Castro", "Luís Castro"], ["Contra", "Cosmin Contra"], ["Jaissle", "Matthias Jaissle"], ["Gerrard", "Steven Gerrard"],
        ["Valverde", "Ernesto Valverde"], ["Míchel", "Míchel Sánchez"], ["Bordalás", "José Bordalás"], ["Pellegrini", "Manuel Pellegrini"], ["Marcelino", "Marcelino Garcia Toral"], ["Garcia Pimienta", "Francisco Javier Garcia Pimienta"], ["Coudet", "Eduardo Coudet"], ["Giráldez", "Claudio Giráldez"], ["Toppmöller", "Dino Toppmöller"], ["Hoeneß", "Sebastian Hoeneß"], ["Seoane", "Gerardo Seoane"], ["Svensson", "Bo Svensson"], ["Breitenreiter", "André Breitenreiter"], ["Haise", "Franck Haise"], ["Sage", "Pierre Sage"], ["Roy", "Eric Roy"], ["Genesio", "Bruno Genesio"], ["Still", "Will Still"], ["Elsner", "Luka Elsner"], ["Kombouaré", "Antoine Kombouaré"], ["Digard", "Didier Digard"], ["Pelissier", "Christophe Pelissier"], ["Dall'Oglio", "Olivier Dall'Oglio"], ["Farioli", "Francesco Farioli"], ["Clement", "Philippe Clement"], ["Priske", "Brian Priske"],
        ["Zidane", "Zinedine Zidane"], ["Allegri", "Massimiliano Allegri"], ["Xavi", "Xavi Hernandez"], ["Tuchel", "Thomas Tuchel"], ["Nagelsmann", "Julian Nagelsmann"], ["Ten Hag", "Erik ten Hag"], ["Potter", "Graham Potter"], ["Southgate", "Gareth Southgate"], ["Sarri", "Maurizio Sarri"], ["Mancini", "Roberto Mancini"], ["Pochettino", "Mauricio Pochettino"], ["Terzic", "Edin Terzic"], ["Favre", "Lucien Favre"], ["Blanc", "Laurent Blanc"], ["Lopetegui", "Julen Lopetegui"], ["Cannavaro", "Fabio Cannavaro"], ["Regragui", "Walid Regragui"], ["Renard", "Hervé Renard"], ["Belmadi", "Djamel Belmadi"], ["Cisse", "Aliou Cissé"], ["Deschamps", "Didier Deschamps"], ["Scaloni", "Lionel Scaloni"], ["Bielsa", "Marcelo Bielsa"], ["Spalletti", "Luciano Spalletti"], ["Koeman", "Ronald Koeman"], ["Martinez", "Roberto Martinez"], ["Gallardo", "Marcelo Gallardo"], ["Sampaoli", "Jorge Sampaoli"]
    ]
}
